[CmdletBinding()]
param(
    [switch]$ConfigOnly,
    [switch]$NoBuild,
    [switch]$KeepRunning
)

$ErrorActionPreference = 'Stop'
$labDir = $PSScriptRoot
$repoRoot = (Resolve-Path (Join-Path $labDir '..\..')).Path
$runtimeDir = Join-Path $labDir 'runtime'
$compose = @('compose', '--file', (Join-Path $labDir 'compose.yaml'))
$labctlImage = 'rusty-weather-distributed-labctl:local'
$completed = $false

function Invoke-Checked {
    param(
        [Parameter(Mandatory = $true)][string]$Program,
        [Parameter(ValueFromRemainingArguments = $true)][string[]]$Arguments
    )
    & $Program @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed ($LASTEXITCODE): $Program $($Arguments -join ' ')"
    }
}

function Save-LabLogs {
    param([string]$Name = 'compose.log')
    $resultsDir = Join-Path $runtimeDir 'results'
    if (-not (Test-Path -LiteralPath $resultsDir)) {
        return
    }
    $logPath = Join-Path $resultsDir $Name
    & docker @compose --profile exercise logs --no-color `
        authority alpha-origin beta-origin `
        authority-edge alpha-edge beta-edge `
        r2-hot cloudflare-turn-api cloudflare-turn-api-edge `
        uploader downloader controller 2>&1 | Set-Content -Encoding utf8 $logPath
}

New-Item -ItemType Directory -Force -Path $runtimeDir | Out-Null
Invoke-Checked docker version

try {
    if (-not $NoBuild) {
        Invoke-Checked docker build `
            --file (Join-Path $labDir 'Dockerfile.labctl') `
            --tag $labctlImage `
            $repoRoot
    }

    if (-not $NoBuild) {
        Invoke-Checked docker run --rm --user '0:0' `
            --volume "${runtimeDir}:/lab" `
            $labctlImage provision /lab
    }
    elseif (-not (Test-Path (Join-Path $runtimeDir 'control\provisioned')) -or
            -not (Test-Path (Join-Path $runtimeDir 'tls\ca.crt'))) {
        throw '-NoBuild requires runtime generated by a prior matching lab build.'
    }
    Invoke-Checked docker @compose config --quiet
    $images = & docker @compose config --images
    if ($LASTEXITCODE -ne 0) {
        throw 'Could not enumerate distributed lab images.'
    }
    foreach ($image in $images) {
        if ($image -notlike 'rusty-weather-distributed-*' -and
            $image -notmatch '@sha256:[0-9a-f]{64}$') {
            throw "External image is not digest-pinned: $image"
        }
    }
    $resolved = (& docker @compose config) -join "`n"
    if ($resolved -notmatch '(?m)^\s+internal: true$') {
        throw 'The distributed lab network is not isolated.'
    }
    $caPatch = Get-Content (Join-Path $labDir 'apply-lab-ca.sh') -Raw
    foreach ($guard in @('PublicInternetOnly', '!is_global_ip', 'DirectCandidateForbidden')) {
        if (-not $caPatch.Contains($guard)) {
            throw "The lab-only CA build guard is missing: $guard"
        }
    }
    if ($ConfigOnly) {
        Write-Host 'Distributed lab compose configuration is valid.'
        $completed = $true
        return
    }

    if (-not $NoBuild) {
        Invoke-Checked docker @compose build authority controller r2-hot
    }

    Invoke-Checked docker @compose up --detach --remove-orphans `
        authority alpha-origin beta-origin `
        authority-edge alpha-edge beta-edge `
        r2-hot cloudflare-turn-api cloudflare-turn-api-edge turn

    Invoke-Checked docker @compose run --rm controller

    foreach ($name in @('traffic-start', 'advertised', 'observer-uploader.ready', 'observer-downloader.ready')) {
        $controlFile = Join-Path $runtimeDir "control\$name"
        if (Test-Path -LiteralPath $controlFile) {
            Remove-Item -LiteralPath $controlFile -Force
        }
    }
    Invoke-Checked docker @compose --profile exercise up --detach `
        uploader downloader observe-uploader observe-downloader traffic-gate
    Invoke-Checked docker @compose --profile exercise wait uploader downloader
    Invoke-Checked docker @compose --profile exercise stop --timeout 5 `
        observe-uploader observe-downloader

    Save-LabLogs
    if ($LASTEXITCODE -ne 0) {
        throw "Could not collect distributed lab logs ($LASTEXITCODE)"
    }

    Invoke-Checked docker @compose --profile verify run --rm packet-verifier
    Invoke-Checked docker @compose --profile verify run --rm result-verifier

    $verification = Get-Content (Join-Path $runtimeDir 'results\verified.json') -Raw
    Write-Host $verification
    Write-Host "Distributed lab passed. Evidence: $runtimeDir\results"
    $completed = $true
}
finally {
    if (-not $completed -and -not $ConfigOnly) {
        & docker @compose --profile exercise stop --timeout 5 `
            observe-uploader observe-downloader 2>&1 | Out-Null
        Save-LabLogs -Name 'failure-compose.log'
        & docker @compose --profile verify run --rm packet-verifier 2>&1 | Out-Null
    }
    if (-not $KeepRunning) {
        & docker @compose --profile exercise --profile verify down `
            --volumes --remove-orphans | Out-Host
    }
    elseif (-not $completed) {
        Write-Warning 'Lab was left running because -KeepRunning was supplied.'
    }
}
