#!/bin/sh
set -eu

lab_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "${lab_dir}/../.." && pwd)
runtime_dir="${lab_dir}/runtime"
compose_file="${lab_dir}/compose.yaml"
labctl_image=rusty-weather-distributed-labctl:local
keep_running=${KEEP_RUNNING:-0}
config_only=${CONFIG_ONLY:-0}
no_build=${NO_BUILD:-0}

cleanup() {
  if [ "${completed:-0}" != 1 ] && [ "${config_only}" != 1 ]; then
    docker compose --file "${compose_file}" --profile exercise stop --timeout 5 \
      observe-uploader observe-downloader >/dev/null 2>&1 || true
    docker compose --file "${compose_file}" --profile exercise logs --no-color \
      authority alpha-origin beta-origin \
      authority-edge alpha-edge beta-edge \
      r2-hot cloudflare-turn-api cloudflare-turn-api-edge \
      uploader downloader controller > "${runtime_dir}/results/failure-compose.log" 2>&1 || true
    docker compose --file "${compose_file}" --profile verify run --rm \
      packet-verifier >/dev/null 2>&1 || true
  fi
  if [ "${keep_running}" != 1 ]; then
    docker compose --file "${compose_file}" --profile exercise --profile verify \
      down --volumes --remove-orphans || true
  fi
}
trap cleanup EXIT INT TERM

mkdir -p "${runtime_dir}"
docker version >/dev/null

if [ "${no_build}" != 1 ]; then
  docker build --file "${lab_dir}/Dockerfile.labctl" \
    --tag "${labctl_image}" "${repo_root}"
fi

if [ "${no_build}" != 1 ]; then
  docker run --rm --user 0:0 \
    --volume "${runtime_dir}:/lab" \
    "${labctl_image}" provision /lab
elif [ ! -f "${runtime_dir}/control/provisioned" ] || [ ! -f "${runtime_dir}/tls/ca.crt" ]; then
  printf '%s\n' 'NO_BUILD=1 requires runtime generated by a prior matching lab build.' >&2
  exit 1
fi

docker compose --file "${compose_file}" config --quiet
docker compose --file "${compose_file}" config --images | while IFS= read -r image; do
  case "${image}" in
    rusty-weather-distributed-*) ;;
    *@sha256:????????????????????????????????????????????????????????????????) ;;
    *) printf 'External image is not digest-pinned: %s\n' "${image}" >&2; exit 1 ;;
  esac
done
docker compose --file "${compose_file}" config | grep -Eq '^ +internal: true$'
for guard in PublicInternetOnly '!is_global_ip' DirectCandidateForbidden; do
  grep -Fq "${guard}" "${lab_dir}/apply-lab-ca.sh"
done
if [ "${config_only}" = 1 ]; then
  printf '%s\n' 'Distributed lab compose configuration is valid.'
  exit 0
fi

if [ "${no_build}" != 1 ]; then
  docker compose --file "${compose_file}" build authority controller r2-hot
fi

docker compose --file "${compose_file}" up --detach --remove-orphans \
  authority alpha-origin beta-origin \
  authority-edge alpha-edge beta-edge \
  r2-hot cloudflare-turn-api cloudflare-turn-api-edge turn

docker compose --file "${compose_file}" run --rm controller

rm -f \
  "${runtime_dir}/control/traffic-start" \
  "${runtime_dir}/control/advertised" \
  "${runtime_dir}/control/observer-uploader.ready" \
  "${runtime_dir}/control/observer-downloader.ready"
docker compose --file "${compose_file}" --profile exercise up --detach \
  uploader downloader observe-uploader observe-downloader traffic-gate
docker compose --file "${compose_file}" --profile exercise wait uploader downloader
docker compose --file "${compose_file}" --profile exercise stop --timeout 5 \
  observe-uploader observe-downloader

docker compose --file "${compose_file}" --profile exercise logs --no-color \
  authority alpha-origin beta-origin \
  authority-edge alpha-edge beta-edge \
  r2-hot cloudflare-turn-api cloudflare-turn-api-edge \
  uploader downloader controller > "${runtime_dir}/results/compose.log" 2>&1

docker compose --file "${compose_file}" --profile verify run --rm packet-verifier
docker compose --file "${compose_file}" --profile verify run --rm result-verifier

cat "${runtime_dir}/results/verified.json"
printf '\nDistributed lab passed. Evidence: %s\n' "${runtime_dir}/results"
completed=1
